name: lazyui
description: "LazyUi is a set of widgets and tools to speed up Flutter app development."
version: 4.3.0
homepage: null

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: assets/fonts/line-awesome.ttf
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
