name: lazyui
description: Make it fast as possible it can.
version: 0.0.1
homepage: https://github.com/ashtav/flutter-lazyui.git
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  animator: ^3.2.0
  cached_network_image: ^3.2.3
  custom_refresh_indicator: ^2.0.1
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.0
  flutter_svg: ^2.0.1
  fluttertoast: ^8.2.1
  http: ^0.13.5
  intl: ^0.17.0
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  stack_trace: ^1.11.0
  teledart: ^0.5.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: assets/fonts/LineAwesome.ttf
          weight: 400
