name: lazyui
description: "LazyUi is a set of widgets and tools to speed up Flutter app development."
version: 4.3.0-rc.1.29
homepage: https://github.com/ashtav/flutter-lazyui.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  device_info_plus: ^11.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  stack_trace: ^1.12.0
  teledart: ^0.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: assets/fonts/line-awesome.ttf
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
