name: lazyui
description: LazyUi is a collection of widgets and utilities designed to simplify and speed up the app development process with Flutter. Simplifying Flutter development for those who prefer efficiency. Fewer lines, cleaner code, quicker results. The essential tool for the streamlined developer.
version: 0.1.0
homepage: https://github.com/ashtav/flutter-lazyui.git

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animator: ^3.3.0
  cached_network_image: ^3.2.3
  custom_refresh_indicator: ^2.0.1
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.1
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.18.0
  path_provider: ^2.0.12
  stack_trace: ^1.11.0
  teledart: ^0.5.4
  tutorial_coach_mark: ^1.2.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: assets/fonts/LineAwesome.ttf
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/TablerIcons.ttf
