name: lazyui
description: LazyUi is a collection of widgets and utilities designed to
  simplify and speed up the app development process with Flutter.
version: 4.2.3
homepage: https://github.com/ashtav/flutter-lazyui.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  ansicolor: ^2.0.3
  cached_network_image: ^3.4.1
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^11.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  stack_trace: ^1.11.1
  teledart: ^0.6.1
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: assets/fonts/line-awesome.ttf
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
